const {contextBridge, ipcRenderer} = require('electron');

const api = {
  open: request => ipcRenderer.invoke('viewer:open', request),
  render: request => ipcRenderer.invoke('viewer:render', request),
  netlist: request => ipcRenderer.invoke('viewer:netlist', request),
  resolve: request => ipcRenderer.invoke('broker:resolve', request),
  domains: () => ipcRenderer.invoke('broker:domains'),
  resourceGet: request => ipcRenderer.invoke('resource:get', request),
  resourceSet: request => ipcRenderer.invoke('resource:set', request),
  resourceCatalog: () => ipcRenderer.invoke('resource:catalog'),
  detail: capabilityId => ipcRenderer.invoke('broker:detail', capabilityId),
  brokerTrace: () => ipcRenderer.invoke('broker:trace'),
  diagnosticRuns: request => ipcRenderer.invoke('agent:log-runs', request),
  diagnosticPage: request => ipcRenderer.invoke('agent:log-page', request),
  diagnosticRecord: request => ipcRenderer.invoke('agent:log-record', request),
  agentStatus: () => ipcRenderer.invoke('agent:status'),
  modelGet: () => ipcRenderer.invoke('model:get'),
  modelSave: request => ipcRenderer.invoke('model:save', request),
  chooseProjectDirectory: () => ipcRenderer.invoke('project:choose-directory'),
  createProject: request => ipcRenderer.invoke('project:create', request),
  projectBindings: () => ipcRenderer.invoke('project:bindings'),
  selectProject: id => ipcRenderer.invoke('project:select', id),
  setProjectDomain: (id, domain) => ipcRenderer.invoke('project:set-domain', {id, domain}),
  setProjectResource: (projectId, kind, id, enabled) => ipcRenderer.invoke('project:set-resource', {projectId, kind, id, enabled}),
  chats: () => ipcRenderer.invoke('chat:list'),
  chatHistory: request => ipcRenderer.invoke('chat:history', request),
  selectChat: id => ipcRenderer.invoke('chat:select', id),
  deleteChat: id => ipcRenderer.invoke('chat:delete', id),
  onChatUpdated: callback => {const listener = () => callback(); ipcRenderer.on('chat:updated', listener); return () => ipcRenderer.removeListener('chat:updated', listener);},
  newChat: () => ipcRenderer.invoke('agent:new'),
  projectFiles: () => ipcRenderer.invoke('project:list'),
  readProjectFile: relative => ipcRenderer.invoke('project:read', relative),
  openProjectFile: relative => ipcRenderer.invoke('project:open', relative),
  validateImages: request => ipcRenderer.invoke('agent:validate-images', request),
  runAgent: (task, chatId) => ipcRenderer.invoke('agent:run', typeof task === 'string' ? {task, chatId} : {...task, chatId: chatId || task.chatId}),
  approveAgent: (id, response) => ipcRenderer.invoke('agent:approve', {id, response}),
  interruptAgent: () => ipcRenderer.invoke('agent:interrupt'),
  onAgentEvent: callback => {const listener = (_event, value) => callback(value); ipcRenderer.on('agent:event', listener); return () => ipcRenderer.removeListener('agent:event', listener);},
};
contextBridge.exposeInMainWorld('viewerHost', api);
